IEEE_MAIN_TEMPLATE = r'''{documentclass_line}
\usepackage{{graphicx}}
\usepackage{{float}}
\usepackage{{placeins}}
\usepackage{{amsmath}}
{preserved_preamble}
{extra_preamble}
\begin{{document}}
\title{{{title}}}
\author{{{authors}}}
\maketitle
\begin{{abstract}}
{abstract}
\end{{abstract}}
{keywords_block}
{extra_frontmatter}
{body}
{bibliography_block}
\end{{document}}
'''

ACM_MAIN_TEMPLATE = r'''{documentclass_line}
\usepackage{{graphicx}}
\usepackage{{float}}
\usepackage{{placeins}}
\usepackage{{amsmath}}
{preserved_preamble}
{extra_preamble}
\begin{{document}}
\title{{{title}}}
{authors}
\begin{{abstract}}
{abstract}
\end{{abstract}}
{keywords_block}
{extra_frontmatter}
\maketitle
\thispagestyle{{plain}}
\pagestyle{{plain}}
{body}
{bibliography_block}
\end{{document}}
'''
